/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package app

import (
	"errors"
	"fmt"
	"github.com/swarleynunez/INVINOS/core"
	"github.com/swarleynunez/INVINOS/core/utils"
	"net/http"
	"strings"
	"time"
)

var (
	ErrUnauthorized = errors.New("unauthorized")
)

func middleware(inner http.Handler, public bool) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		// Check if the route is public or private
		if !public {
			// Auth by API token
			ah := r.Header.Get("Authorization")
			token := strings.TrimPrefix(ah, "Bearer ")
			if ah == "" || !strings.HasPrefix(ah, "Bearer ") || core.Instances[token] == "" {
				w.WriteHeader(http.StatusUnauthorized)
				utils.CheckError(ErrUnauthorized, utils.WarningMode)
				return
			}
		}

		// Execute request
		inner.ServeHTTP(w, r)

		// Debug
		fmt.Printf(
			"[%d] %s %s %s\n",
			time.Now().UnixMilli(),
			r.Method,
			r.RequestURI,
			time.Since(start),
		)
	})
}
