/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Certificado de producto con sulfitos añadidos
type ConSulfitosAdd struct {
	// Tipo de certificado
	Tipo string `json:"tipo,omitempty"`
	// Valor máximo de sulfitos añadidos en mg/l
	Valor float64 `json:"valor,omitempty"`

	Certificado *CertTemplateAdd `json:"certificado,omitempty"`
}
