/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Lote de producto
type Lote struct {
	NumLote string `json:"num_lote"`
	// Fecha de caducidad
	Caducidad string `json:"caducidad"`
	// Fecha de envasado
	FechaEnvasado string `json:"fecha_envasado"`
	// URL de trazabilidad del lote. Con esta se podrá hacer la trazabilidad del lote en la blockchain.
	Url string `json:"url"`
}
