/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"os"
)

// Documento almacenado en IPFS
type IpfSfileAdd struct {
	File **os.File `json:"file"`
	// Nombre del documento
	Name string `json:"name,omitempty"`
}
