/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Etiqueta de producto
type Etiqueta struct {
	// Categoría del vino: DOP, IGP, Vino de la Tierra, Vino de Mesa
	Categoria string `json:"categoria,omitempty"`
	// Graduación alcohólica %vol
	Ga float64 `json:"ga,omitempty"`
	// Bodega o Cooperativa que produjo el vino
	Procedencia string `json:"procedencia,omitempty"`
	// Nombre del embotellador
	Embotellador string `json:"embotellador,omitempty"`
	// Lote de producción del vino
	Lote string `json:"lote,omitempty"`

	Nutricion *EtiquetaNutricion `json:"nutricion,omitempty"`
	// Fecha de embotellado del vino
	Fecha string `json:"fecha,omitempty"`
}
