/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Certificado de Indicación Geográfica Protegida
type CertIgp struct {
	// Tipo de certificado
	Type_ string `json:"type_igp,omitempty"`
	// Nombre de la IGP
	Name string `json:"name_igp,omitempty"`

	Certificado *CertTemplate `json:"certificado_igp,omitempty"`
}
