/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type EtiquetaNutricion struct {
	// Valor energético del vino en kcal/100ml
	VEnergetico float64 `json:"v_energetico,omitempty"`
	// Alergias o Intolerancias que puede contener el vino
	Alergias string `json:"alergias,omitempty"`
	// Ingredientes que contiene el vino
	Ingredientes string `json:"ingredientes,omitempty"`
	// Declaración nutricional del vino
	Declaracion string `json:"declaracion,omitempty"`
}
