/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Información sobre el depósito
type InfoDeposito struct {
	Tipo string `json:"tipo,omitempty"`

	Dimensiones *InfoDepositoDimensiones `json:"dimensiones,omitempty"`
	// Material del que está hecho el depósito
	Material string `json:"material,omitempty"`
}
