/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type InfoVino struct {
	// Tipo de vino según color de vino
	Color string `json:"color_vino,omitempty"`

	Quimica *InfoVinoAddQuimica `json:"quimica_vino,omitempty"`
	// Subtipo de vino según crianza
	Elaboracion string `json:"elaboracion,omitempty"`
	// Variedades de uva que componen el vino y sus añadas
	Composicion []InfoComponente `json:"composicion_vino,omitempty"`
	// Certificados del vino subidos a IPFS
	Certificados []AnyOfInfoVinoCertificadosItems `json:"certificados_vino,omitempty"`
}
