/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Información sobre la barrica
type InfoBarrica struct {
	Tipo string `json:"tipo,omitempty"`

	Dimensiones *InfoBarricaDimensiones `json:"dimensiones,omitempty"`
	// Material del que está hecha la barrica
	Material string `json:"material,omitempty"`
	// Tostado de la barrica
	Tostado string `json:"tostado,omitempty"`
	// Edad de la barrica en años
	Edad float64 `json:"edad,omitempty"`
}
