/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Empresa struct {
	Id string `json:"id"`
	// Nombre de la empresa
	Nombre string `json:"nombre"`
	// Código de identificación fiscal
	Cif string `json:"cif"`
	// Tipo de empresa
	TipoStd string `json:"tipo_std,omitempty"`
	// Tipo de empresa
	TipoOtros string `json:"tipo_otros,omitempty"`

	Info *InfoEmpresa `json:"info,omitempty"`
}
