/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Procesado struct {
	Id string `json:"id"`
	// Tipo de procesado
	Tipo string `json:"tipo"`
	// Fecha de procesado
	Fecha string `json:"fecha"`

	Producto *Producto `json:"producto"`

	Merma *ProductoCantidad `json:"merma"`

	AContenedor *Contenedor `json:"a_contenedor"`
	// Información adicional sobre el procesado
	Info string `json:"info,omitempty"`
}
