/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type InfoEmpresaAdd struct {
	// Dirección de la empresa
	Direccion string `json:"direccion,omitempty"`
	// Teléfono de la empresa
	Telefono string `json:"telefono,omitempty"`
	// Email de la empresa
	Email string `json:"email,omitempty"`
	// Página web de la empresa
	Web string `json:"web,omitempty"`
}
