/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Producto que se ha vendido. Es un producto con un \\#Lote que se utiliza para trazar el producto. El resto de información es la misma que la de Producto.
type ProductoVendido struct {
	Producto *Producto `json:"producto,omitempty"`

	Lote *Lote `json:"lote,omitempty"`
}
