/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Certificado de producto
type CertTemplateAdd struct {
	// Nombre del certificado
	Name string `json:"name,omitempty"`
	// Certificado subido a IPFS
	Files []IpfSfileAdd `json:"files,omitempty"`
	// Nombre de la certificadora
	Certificadora string `json:"certificadora,omitempty"`
	// Fecha de certificación
	FechaCertificacion string `json:"fecha_certificacion,omitempty"`
	// Fecha de expiración del certificado
	FechaExpiracion string `json:"fecha_expiracion,omitempty"`
	// Información adicional sobre el certificado
	Info string `json:"info,omitempty"`
}
