/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Sistema de producción ecológica natural
type SistProduccionNatural struct {
	// Tipo de certificado
	Tipo string `json:"tipo,omitempty"`

	Certificado *CertTemplate `json:"certificado,omitempty"`
}
