/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Cualquier tipo de contenedor de productos
type Contenedor struct {
	Id string `json:"id"`

	Info *OneOfContenedorInfo `json:"info,omitempty"`
}
