/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Información sobre la parcela de cultivo
type ParcelaAdd struct {
	// Nombre de la parcela
	Name string `json:"name"`
	// Localización de la parcela
	Localizacion []AnyOfParcelaAddLocalizacionItems `json:"localizacion,omitempty"`
	// Certificados de la parcela subidos a IPFS
	Certificados []AnyOfParcelaAddCertificadosItems `json:"certificados,omitempty"`
}
