/*
 * API for INVINOS blockchain broker
 *
 * Esta es la API para el brocker de INVINOS con el que hay que interactuar para realizar transacciones en la blockchain.
 *
 * API version: 1.0
 * Contact: francisco.delicado@uclm.es
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Información sobre la botella
type InfoBotella struct {
	// Tipo de botella
	TipoStd string `json:"tipo_std,omitempty"`
	// Tipo de botella
	TipoOtros string `json:"tipo_otros,omitempty"`

	Dimensiones *InfoBotellaDimensiones `json:"dimensiones,omitempty"`
	// Material del que está hecha la botella
	Material string `json:"material,omitempty"`
	// Color de la botella
	Color string `json:"color,omitempty"`
	// Tipo de tapón de la botella
	Tapn string `json:"tapón,omitempty"`

	Etiqueta *Etiqueta `json:"etiqueta,omitempty"`
}
